"""fix invoice models

Revision ID: 1d2f47161261
Revises: 9cc08965ffc1
Create Date: 2026-01-04 20:37:18.977864
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1d2f47161261'
down_revision = '9cc08965ffc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
