"""add customers

Revision ID: 3b902d853437
Revises: 45fcd7829d4b
Create Date: 2026-01-03 19:28:40.561259
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3b902d853437'
down_revision = '45fcd7829d4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
