"""add invoices

Revision ID: 9cc08965ffc1
Revises: c69722e9dbf4
Create Date: 2026-01-04 00:47:13.948232
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9cc08965ffc1'
down_revision = 'c69722e9dbf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
