"""add items

Revision ID: c69722e9dbf4
Revises: 3b902d853437
Create Date: 2026-01-03 19:31:19.164063
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c69722e9dbf4'
down_revision = '3b902d853437'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
